# Generated by Django 4.0.10 on 2024-01-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('address_detail', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
