# Generated by Django 4.0.10 on 2024-01-02 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=255, verbose_name='주문자 성함')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='받는분 성함')),
                ('recipient_tel', models.CharField(max_length=255, verbose_name='받는분 연락처')),
                ('address', models.CharField(max_length=255, verbose_name='주소')),
                ('address_detail', models.CharField(max_length=255, verbose_name='상세주소')),
                ('zip_code', models.CharField(max_length=255, verbose_name='우편번호')),
                ('order_request', models.TextField(verbose_name='요청사항')),
                ('shipping_fee', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.IntegerField(choices=[(1, '무통장입금'), (2, '신용카드'), (3, '삼성페이')])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255, verbose_name='상품명')),
                ('sale_price', models.PositiveIntegerField(default=0, verbose_name='판매가')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='개수')),
                ('thumbnail', models.URLField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
